## Numpy Practice

In [1]:
import numpy as np

In [3]:
a1 = np.random.randint(10, size=10)
print(a1)
a2 = np.random.randint(10, size=(5, 5))
print(a2)
a3 = np.random.randint(10, size=(3, 3, 2))
print(a3)

[2 3 0 0 3 9 8 3 5 5]
[[6 5 0 9 7]
 [3 7 0 6 3]
 [2 1 8 7 1]
 [2 6 1 2 0]
 [0 1 5 8 8]]
[[[9 4]
  [4 6]
  [3 2]]

 [[1 2]
  [9 6]
  [2 0]]

 [[5 3]
  [3 6]
  [0 7]]]


In [4]:
a1.shape, a1.dtype, type(a1)


((10,), dtype('int64'), numpy.ndarray)

In [5]:
a2.shape, a2.dtype, type(a2)

((5, 5), dtype('int64'), numpy.ndarray)

In [6]:
a3.shape, a3.dtype, type(a3)

((3, 3, 2), dtype('int64'), numpy.ndarray)

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(a2, columns=['a', 'b', 'c', 'd', 'e'])
df

a  b  c  d  e
0  6  5  0  9  7
1  3  7  0  6  3
2  2  1  8  7  1
3  2  6  1  2  0
4  0  1  5  8  8

In [9]:
ones_sample = np.ones((10, 2))
ones_sample

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
zeros_sample = np.zeros((7, 2, 3))
zeros_sample

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
sample_array_1 = np.array(range(0, 100, 3))
sample_array_1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
sample_array_2 = np.random.randint(0, 10, size=(7, 2))
sample_array_2

array([[5, 8],
       [2, 2],
       [7, 9],
       [9, 9],
       [9, 5],
       [6, 6],
       [7, 1]])

In [13]:
sample_array_3 = np.random.random((3, 5))
sample_array_3

array([[0.93484816, 0.31652971, 0.89529494, 0.88824021, 0.80923481],
       [0.80818069, 0.18741674, 0.50863877, 0.82085261, 0.10264668],
       [0.22573427, 0.14817935, 0.01083996, 0.08368421, 0.13700059]])

In [15]:
np.random.seed(42)
sample_array_4 = np.random.randint(0, 11, size=(4, 6))
sample_array_4

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

In [16]:
sample_array_5 = np.random.randint(1, 11, size=(3, 7 ))
sample_array_5

array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7],
       [ 5,  9,  7,  2,  4,  9,  2]])

In [20]:
# find unique values in sample_array_5
np.unique(sample_array_5)


array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [22]:
# Find the 0'th index of the latest array you created
sample_array_5[0]

array([ 1, 10,  6,  9,  1, 10,  3])

In [23]:
sample_array_5[:2]

array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7]])

In [24]:
sample_array_5[:2, :2]

array([[ 1, 10],
       [ 7,  4]])

In [25]:
sample_array_6 = np.random.randint(0, 11, size=(3, 5))
sample_ones = np.ones((3, 5))


In [26]:
sample_array_6

array([[9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1]])

In [27]:
sample_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
sample_array_6 + sample_ones

array([[10.,  9., 10.,  5.,  2.],
       [ 4.,  7.,  8.,  3.,  1.],
       [ 4.,  2.,  8.,  4.,  2.]])

In [29]:
sample_ones_2 = np.ones((5, 3))

In [30]:
sample_array_6 + sample_ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [31]:
sample_ones_3 = np.ones((3, 5))

In [32]:
sample_array_6 - sample_ones_3

array([[ 8.,  7.,  8.,  3.,  0.],
       [ 2.,  5.,  6.,  1., -1.],
       [ 2.,  0.,  6.,  2.,  0.]])

In [33]:
sample_array_6 * sample_ones_3

array([[9., 8., 9., 4., 1.],
       [3., 6., 7., 2., 0.],
       [3., 1., 7., 3., 1.]])

In [34]:
sample_array_6 ** 2

array([[81, 64, 81, 16,  1],
       [ 9, 36, 49,  4,  0],
       [ 9,  1, 49,  9,  1]])

In [35]:
np.square(sample_array_6)

array([[81, 64, 81, 16,  1],
       [ 9, 36, 49,  4,  0],
       [ 9,  1, 49,  9,  1]])

In [36]:
np.mean(sample_array_6)

4.266666666666667

In [37]:
np.max(sample_array_6)

9

In [38]:
np.min(sample_array_6)

0

In [39]:
np.std(sample_array_6)

3.0214051182999095

In [40]:
np.var(sample_array_6)

9.12888888888889

In [42]:
sample_reshaped = sample_array_6.reshape(3, 5, 1)

In [43]:
sample_reshaped.T

array([[[9, 3, 3],
        [8, 6, 1],
        [9, 7, 7],
        [4, 2, 3],
        [1, 0, 1]]])

In [44]:
sample_reshaped

array([[[9],
        [8],
        [9],
        [4],
        [1]],

       [[3],
        [6],
        [7],
        [2],
        [0]],

       [[3],
        [1],
        [7],
        [3],
        [1]]])

In [ ]:
# Create an array of normally distributed random numbers
